# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_files/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 920)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self._progress_bar = QtWidgets.QProgressBar(self.central_widget)
        self._progress_bar.setGeometry(QtCore.QRect(0, 870, 1195, 21))
        self._progress_bar.setProperty("value", 0)
        self._progress_bar.setObjectName("_progress_bar")
        self._tab_widget = QtWidgets.QTabWidget(self.central_widget)
        self._tab_widget.setGeometry(QtCore.QRect(840, 0, 360, 861))
        self._tab_widget.setIconSize(QtCore.QSize(15, 15))
        self._tab_widget.setObjectName("_tab_widget")
        self._sim_settings_tab = QtWidgets.QWidget()
        self._sim_settings_tab.setObjectName("_sim_settings_tab")
        self._sim_settings_scroll_area = QtWidgets.QScrollArea(self._sim_settings_tab)
        self._sim_settings_scroll_area.setGeometry(QtCore.QRect(0, 0, 360, 831))
        self._sim_settings_scroll_area.setWidgetResizable(True)
        self._sim_settings_scroll_area.setObjectName("_sim_settings_scroll_area")
        self._sim_settings_widget = QtWidgets.QWidget()
        self._sim_settings_widget.setGeometry(QtCore.QRect(0, 0, 358, 829))
        self._sim_settings_widget.setObjectName("_sim_settings_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self._sim_settings_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 0, 323, 288))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.vertical_layout.setObjectName("vertical_layout")
        self.line_10 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.vertical_layout.addWidget(self.line_10)
        self.sim_settings_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sim_settings_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_settings_label.setObjectName("sim_settings_label")
        self.vertical_layout.addWidget(self.sim_settings_label)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.vertical_layout.addWidget(self.line_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout.setContentsMargins(10, 5, 10, 5)
        self.formLayout.setHorizontalSpacing(32)
        self.formLayout.setObjectName("formLayout")
        self.sim_duration_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sim_duration_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_duration_label.setObjectName("sim_duration_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sim_duration_label)
        self._sim_duration_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self._sim_duration_line_edit.setObjectName("_sim_duration_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self._sim_duration_line_edit)
        self.vertical_layout.addLayout(self.formLayout)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.vertical_layout.addWidget(self.line_3)
        self.wind_settings_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.wind_settings_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_settings_label.setObjectName("wind_settings_label")
        self.vertical_layout.addWidget(self.wind_settings_label)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.vertical_layout.addWidget(self.line_6)
        self.wind_form_layout = QtWidgets.QFormLayout()
        self.wind_form_layout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.wind_form_layout.setContentsMargins(10, 5, 10, 5)
        self.wind_form_layout.setHorizontalSpacing(47)
        self.wind_form_layout.setVerticalSpacing(10)
        self.wind_form_layout.setObjectName("wind_form_layout")
        self.wind_speed_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.wind_speed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_speed_label.setObjectName("wind_speed_label")
        self.wind_form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.wind_speed_label)
        self._wind_speed_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self._wind_speed_line_edit.setObjectName("_wind_speed_line_edit")
        self.wind_form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self._wind_speed_line_edit)
        self.wind_direction_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.wind_direction_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_direction_label.setObjectName("wind_direction_label")
        self.wind_form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.wind_direction_label)
        self._wind_direction_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self._wind_direction_line_edit.setObjectName("_wind_direction_line_edit")
        self.wind_form_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self._wind_direction_line_edit)
        self.vertical_layout.addLayout(self.wind_form_layout)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.vertical_layout.addWidget(self.line_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.vertical_layout.addLayout(self.horizontalLayout_7)
        self.line_14 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.vertical_layout.addWidget(self.line_14)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(10, 5, 10, 5)
        self.formLayout_2.setHorizontalSpacing(15)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self._ambient_temp_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self._ambient_temp_line_edit.setObjectName("_ambient_temp_line_edit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self._ambient_temp_line_edit)
        self.vertical_layout.addLayout(self.formLayout_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vertical_layout.addWidget(self.line)
        self._sim_settings_scroll_area.setWidget(self._sim_settings_widget)
        self._tab_widget.addTab(self._sim_settings_tab, "")
        self._fl_type_lgnd_tab = QtWidgets.QWidget()
        self._fl_type_lgnd_tab.setObjectName("_fl_type_lgnd_tab")
        self.fuel_type_scroll_area = QtWidgets.QScrollArea(self._fl_type_lgnd_tab)
        self.fuel_type_scroll_area.setGeometry(QtCore.QRect(0, 0, 360, 831))
        self.fuel_type_scroll_area.setWidgetResizable(True)
        self.fuel_type_scroll_area.setObjectName("fuel_type_scroll_area")
        self.fuel_type_scroll_area_widget_contents = QtWidgets.QWidget()
        self.fuel_type_scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 358, 829))
        self.fuel_type_scroll_area_widget_contents.setObjectName("fuel_type_scroll_area_widget_contents")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.fuel_type_scroll_area_widget_contents)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 335, 331))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.fuel_type_legend_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.fuel_type_legend_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fuel_type_legend_label.setObjectName("fuel_type_legend_label")
        self.verticalLayout_2.addWidget(self.fuel_type_legend_label)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self._fl_type_lgnd_scroll_area = QtWidgets.QScrollArea(self.verticalLayoutWidget_2)
        self._fl_type_lgnd_scroll_area.setWidgetResizable(True)
        self._fl_type_lgnd_scroll_area.setObjectName("_fl_type_lgnd_scroll_area")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 331, 101))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self._fl_type_lgnd_scroll_area.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self._fl_type_lgnd_scroll_area)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_9 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_2.addWidget(self.line_9)
        self.modify_fuel_map_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.modify_fuel_map_label.setAlignment(QtCore.Qt.AlignCenter)
        self.modify_fuel_map_label.setObjectName("modify_fuel_map_label")
        self.verticalLayout_2.addWidget(self.modify_fuel_map_label)
        self.line_12 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_2.addWidget(self.line_12)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self._x_rng_min_fl_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self._x_rng_min_fl_line_edit.setObjectName("_x_rng_min_fl_line_edit")
        self.gridLayout.addWidget(self._x_rng_min_fl_line_edit, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self._y_rng_max_fl_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self._y_rng_max_fl_line_edit.setPlaceholderText("")
        self._y_rng_max_fl_line_edit.setObjectName("_y_rng_max_fl_line_edit")
        self.gridLayout.addWidget(self._y_rng_max_fl_line_edit, 1, 4, 1, 1)
        self._x_rng_max_fl_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self._x_rng_max_fl_line_edit.setObjectName("_x_rng_max_fl_line_edit")
        self.gridLayout.addWidget(self._x_rng_max_fl_line_edit, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self._y_rng_min_fl_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self._y_rng_min_fl_line_edit.setObjectName("_y_rng_min_fl_line_edit")
        self.gridLayout.addWidget(self._y_rng_min_fl_line_edit, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self._fl_type_combo_box = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self._fl_type_combo_box.setObjectName("_fl_type_combo_box")
        self._fl_type_combo_box.addItem("")
        self._fl_type_combo_box.addItem("")
        self.horizontalLayout_3.addWidget(self._fl_type_combo_box)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_13 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_2.addWidget(self.line_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.modify_fuel_map_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.modify_fuel_map_button.setObjectName("modify_fuel_map_button")
        self.horizontalLayout_4.addWidget(self.modify_fuel_map_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line_11 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_2.addWidget(self.line_11)
        self.fuel_type_scroll_area.setWidget(self.fuel_type_scroll_area_widget_contents)
        self._tab_widget.addTab(self._fl_type_lgnd_tab, "")
        self.ignition_point_legend_tab = QtWidgets.QWidget()
        self.ignition_point_legend_tab.setObjectName("ignition_point_legend_tab")
        self.ignition_point_scroll_area = QtWidgets.QScrollArea(self.ignition_point_legend_tab)
        self.ignition_point_scroll_area.setGeometry(QtCore.QRect(0, 0, 361, 831))
        self.ignition_point_scroll_area.setWidgetResizable(True)
        self.ignition_point_scroll_area.setObjectName("ignition_point_scroll_area")
        self.ignition_point_scroll_area_widget_contents = QtWidgets.QWidget()
        self.ignition_point_scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 359, 829))
        self.ignition_point_scroll_area_widget_contents.setObjectName("ignition_point_scroll_area_widget_contents")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.ignition_point_scroll_area_widget_contents)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 0, 321, 381))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_20 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_4.addWidget(self.line_20)
        self.ign_pointlegend_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.ign_pointlegend_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ign_pointlegend_label.setObjectName("ign_pointlegend_label")
        self.verticalLayout_4.addWidget(self.ign_pointlegend_label)
        self.line_21 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_4.addWidget(self.line_21)
        self.ignition_point_map_legend_scroll_area = QtWidgets.QScrollArea(self.verticalLayoutWidget_4)
        self.ignition_point_map_legend_scroll_area.setWidgetResizable(True)
        self.ignition_point_map_legend_scroll_area.setObjectName("ignition_point_map_legend_scroll_area")
        self.ingition_point_map_legend_scroll_area_widget_contents = QtWidgets.QWidget()
        self.ingition_point_map_legend_scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 317, 99))
        self.ingition_point_map_legend_scroll_area_widget_contents.setObjectName("ingition_point_map_legend_scroll_area_widget_contents")
        self.ignition_point_map_legend_scroll_area.setWidget(self.ingition_point_map_legend_scroll_area_widget_contents)
        self.verticalLayout_4.addWidget(self.ignition_point_map_legend_scroll_area)
        self.line_22 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.verticalLayout_4.addWidget(self.line_22)
        self.modify_ignition_point_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.modify_ignition_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.modify_ignition_point_label.setObjectName("modify_ignition_point_label")
        self.verticalLayout_4.addWidget(self.modify_ignition_point_label)
        self.line_23 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.verticalLayout_4.addWidget(self.line_23)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self._ign_pt_axis_combo_box = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self._ign_pt_axis_combo_box.setObjectName("_ign_pt_axis_combo_box")
        self._ign_pt_axis_combo_box.addItem("")
        self._ign_pt_axis_combo_box.addItem("")
        self.horizontalLayout_5.addWidget(self._ign_pt_axis_combo_box)
        spacerItem6 = QtWidgets.QSpacerItem(125, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self._ign_pt_row_col_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self._ign_pt_row_col_line_edit.setObjectName("_ign_pt_row_col_line_edit")
        self.gridLayout_3.addWidget(self._ign_pt_row_col_line_edit, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self._ign_pt_rng_max_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self._ign_pt_rng_max_line_edit.setPlaceholderText("")
        self._ign_pt_rng_max_line_edit.setObjectName("_ign_pt_rng_max_line_edit")
        self.gridLayout_3.addWidget(self._ign_pt_rng_max_line_edit, 0, 3, 1, 1)
        self._ign_pt_rng_min_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self._ign_pt_rng_min_line_edit.setText("")
        self._ign_pt_rng_min_line_edit.setObjectName("_ign_pt_rng_min_line_edit")
        self.gridLayout_3.addWidget(self._ign_pt_rng_min_line_edit, 0, 1, 1, 1)
        self._ign_pt_t_start_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self._ign_pt_t_start_line_edit.setObjectName("_ign_pt_t_start_line_edit")
        self.gridLayout_3.addWidget(self._ign_pt_t_start_line_edit, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self._ign_pt_t_end_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self._ign_pt_t_end_line_edit.setObjectName("_ign_pt_t_end_line_edit")
        self.gridLayout_3.addWidget(self._ign_pt_t_end_line_edit, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self._ign_pt_add_rm_combo_box = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self._ign_pt_add_rm_combo_box.setObjectName("_ign_pt_add_rm_combo_box")
        self._ign_pt_add_rm_combo_box.addItem("")
        self._ign_pt_add_rm_combo_box.addItem("")
        self.horizontalLayout_9.addWidget(self._ign_pt_add_rm_combo_box)
        spacerItem7 = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.line_24 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.verticalLayout_4.addWidget(self.line_24)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem8 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.modify_ign_pts_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.modify_ign_pts_button.setObjectName("modify_ign_pts_button")
        self.horizontalLayout_10.addWidget(self.modify_ign_pts_button)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.line_25 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.verticalLayout_4.addWidget(self.line_25)
        self.ignition_point_scroll_area.setWidget(self.ignition_point_scroll_area_widget_contents)
        self._tab_widget.addTab(self.ignition_point_legend_tab, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 821, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._sim_title_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self._sim_title_label.setObjectName("_sim_title_label")
        self.horizontalLayout_2.addWidget(self._sim_title_label)
        MainWindow.setCentralWidget(self.central_widget)
        self._menu_bar = QtWidgets.QMenuBar(MainWindow)
        self._menu_bar.setGeometry(QtCore.QRect(0, 0, 1200, 20))
        self._menu_bar.setDefaultUp(False)
        self._menu_bar.setNativeMenuBar(False)
        self._menu_bar.setObjectName("_menu_bar")
        self.menu_file = QtWidgets.QMenu(self._menu_bar)
        self.menu_file.setObjectName("menu_file")
        self.menu_export = QtWidgets.QMenu(self._menu_bar)
        self.menu_export.setObjectName("menu_export")
        self.menu_settings = QtWidgets.QMenu(self._menu_bar)
        self.menu_settings.setObjectName("menu_settings")
        self.menu_help = QtWidgets.QMenu(self._menu_bar)
        self.menu_help.setObjectName("menu_help")
        self.menu_simulation = QtWidgets.QMenu(self._menu_bar)
        self.menu_simulation.setObjectName("menu_simulation")
        self.menu_import = QtWidgets.QMenu(self._menu_bar)
        self.menu_import.setObjectName("menu_import")
        MainWindow.setMenuBar(self._menu_bar)
        self.action_create_environment = QtWidgets.QAction(MainWindow)
        self.action_create_environment.setObjectName("action_create_environment")
        self.action_import_environment = QtWidgets.QAction(MainWindow)
        self.action_import_environment.setObjectName("action_import_environment")
        self.action_export_simulation = QtWidgets.QAction(MainWindow)
        self.action_export_simulation.setObjectName("action_export_simulation")
        self.action_export_summary_file = QtWidgets.QAction(MainWindow)
        self.action_export_summary_file.setObjectName("action_export_summary_file")
        self.action_export_environment = QtWidgets.QAction(MainWindow)
        self.action_export_environment.setObjectName("action_export_environment")
        self.action_import_simulation = QtWidgets.QAction(MainWindow)
        self.action_import_simulation.setObjectName("action_import_simulation")
        self.action_import_summary_file = QtWidgets.QAction(MainWindow)
        self.action_import_summary_file.setObjectName("action_import_summary_file")
        self.action_select_output_files = QtWidgets.QAction(MainWindow)
        self.action_select_output_files.setObjectName("action_select_output_files")
        self.action_run_sim = QtWidgets.QAction(MainWindow)
        self.action_run_sim.setObjectName("action_run_sim")
        self.action_view_sim = QtWidgets.QAction(MainWindow)
        self.action_view_sim.setObjectName("action_view_sim")
        self.action_user_settings = QtWidgets.QAction(MainWindow)
        self.action_user_settings.setObjectName("action_user_settings")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_import_fuel_map = QtWidgets.QAction(MainWindow)
        self.action_import_fuel_map.setObjectName("action_import_fuel_map")
        self.action_import_dem = QtWidgets.QAction(MainWindow)
        self.action_import_dem.setObjectName("action_import_dem")
        self.action_export_fuel_map = QtWidgets.QAction(MainWindow)
        self.action_export_fuel_map.setObjectName("action_export_fuel_map")
        self.action_export_dem = QtWidgets.QAction(MainWindow)
        self.action_export_dem.setObjectName("action_export_dem")
        self.action_ascii_to_fds = QtWidgets.QAction(MainWindow)
        self.action_ascii_to_fds.setObjectName("action_ascii_to_fds")
        self.menu_file.addAction(self.action_create_environment)
        self.menu_export.addAction(self.action_export_fuel_map)
        self.menu_export.addAction(self.action_export_dem)
        self.menu_settings.addAction(self.action_user_settings)
        self.menu_help.addAction(self.action_about)
        self.menu_simulation.addAction(self.action_run_sim)
        self.menu_simulation.addAction(self.action_view_sim)
        self.menu_import.addAction(self.action_import_environment)
        self.menu_import.addAction(self.action_import_fuel_map)
        self.menu_import.addAction(self.action_import_dem)
        self._menu_bar.addAction(self.menu_file.menuAction())
        self._menu_bar.addAction(self.menu_import.menuAction())
        self._menu_bar.addAction(self.menu_export.menuAction())
        self._menu_bar.addAction(self.menu_simulation.menuAction())
        self._menu_bar.addAction(self.menu_settings.menuAction())
        self._menu_bar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self._tab_widget.setCurrentIndex(0)
        self._fl_type_combo_box.setCurrentIndex(0)
        self._ign_pt_axis_combo_box.setCurrentIndex(0)
        self._ign_pt_add_rm_combo_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self._tab_widget, self._sim_settings_scroll_area)
        MainWindow.setTabOrder(self._sim_settings_scroll_area, self._sim_duration_line_edit)
        MainWindow.setTabOrder(self._sim_duration_line_edit, self._wind_speed_line_edit)
        MainWindow.setTabOrder(self._wind_speed_line_edit, self._wind_direction_line_edit)
        MainWindow.setTabOrder(self._wind_direction_line_edit, self._ambient_temp_line_edit)
        MainWindow.setTabOrder(self._ambient_temp_line_edit, self.fuel_type_scroll_area)
        MainWindow.setTabOrder(self.fuel_type_scroll_area, self._fl_type_lgnd_scroll_area)
        MainWindow.setTabOrder(self._fl_type_lgnd_scroll_area, self._x_rng_min_fl_line_edit)
        MainWindow.setTabOrder(self._x_rng_min_fl_line_edit, self._x_rng_max_fl_line_edit)
        MainWindow.setTabOrder(self._x_rng_max_fl_line_edit, self._y_rng_min_fl_line_edit)
        MainWindow.setTabOrder(self._y_rng_min_fl_line_edit, self._y_rng_max_fl_line_edit)
        MainWindow.setTabOrder(self._y_rng_max_fl_line_edit, self._fl_type_combo_box)
        MainWindow.setTabOrder(self._fl_type_combo_box, self.modify_fuel_map_button)
        MainWindow.setTabOrder(self.modify_fuel_map_button, self.ignition_point_map_legend_scroll_area)
        MainWindow.setTabOrder(self.ignition_point_map_legend_scroll_area, self._ign_pt_axis_combo_box)
        MainWindow.setTabOrder(self._ign_pt_axis_combo_box, self._ign_pt_rng_min_line_edit)
        MainWindow.setTabOrder(self._ign_pt_rng_min_line_edit, self._ign_pt_rng_max_line_edit)
        MainWindow.setTabOrder(self._ign_pt_rng_max_line_edit, self._ign_pt_row_col_line_edit)
        MainWindow.setTabOrder(self._ign_pt_row_col_line_edit, self._ign_pt_t_start_line_edit)
        MainWindow.setTabOrder(self._ign_pt_t_start_line_edit, self._ign_pt_t_end_line_edit)
        MainWindow.setTabOrder(self._ign_pt_t_end_line_edit, self._ign_pt_add_rm_combo_box)
        MainWindow.setTabOrder(self._ign_pt_add_rm_combo_box, self.modify_ign_pts_button)
        MainWindow.setTabOrder(self.modify_ign_pts_button, self.ignition_point_scroll_area)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FireScape Rx"))
        self.sim_settings_label.setText(_translate("MainWindow", "Simulation Settings"))
        self.sim_duration_label.setToolTip(_translate("MainWindow", "Duration of the simulation in seconds"))
        self.sim_duration_label.setText(_translate("MainWindow", "Simulation Duration (s)"))
        self.wind_settings_label.setText(_translate("MainWindow", "Wind Settings"))
        self.wind_speed_label.setToolTip(_translate("MainWindow", "Wind speed in miles per hour"))
        self.wind_speed_label.setText(_translate("MainWindow", "Wind Speed (mph)"))
        self._wind_speed_line_edit.setToolTip(_translate("MainWindow", "Wind speed in miles per hour"))
        self.wind_direction_label.setToolTip(_translate("MainWindow", "Meterological wind direction in degrees"))
        self.wind_direction_label.setText(_translate("MainWindow", "Wind Direction (deg)"))
        self._wind_direction_line_edit.setToolTip(_translate("MainWindow", "Meterological wind direction in degrees"))
        self.label_6.setText(_translate("MainWindow", "Environmental Conditions"))
        self.label_7.setText(_translate("MainWindow", "Ambient Temperature (F) "))
        self._tab_widget.setTabText(self._tab_widget.indexOf(self._sim_settings_tab), _translate("MainWindow", "Simulation Settings"))
        self.fuel_type_legend_label.setText(_translate("MainWindow", "Fuel Type Legend:"))
        self.modify_fuel_map_label.setText(_translate("MainWindow", "Modify Fuel Map:"))
        self.label_2.setText(_translate("MainWindow", "Y range:"))
        self.label.setText(_translate("MainWindow", "X range:"))
        self.label_5.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "-"))
        self.label_3.setText(_translate("MainWindow", "Fuel Type:"))
        self._fl_type_combo_box.setCurrentText(_translate("MainWindow", "Untreated"))
        self._fl_type_combo_box.setItemText(0, _translate("MainWindow", "Untreated"))
        self._fl_type_combo_box.setItemText(1, _translate("MainWindow", "Treated"))
        self.modify_fuel_map_button.setText(_translate("MainWindow", "Modify"))
        self._tab_widget.setTabText(self._tab_widget.indexOf(self._fl_type_lgnd_tab), _translate("MainWindow", "Fuel Map"))
        self.ign_pointlegend_label.setText(_translate("MainWindow", "Ignition Point Map Legend:"))
        self.modify_ignition_point_label.setText(_translate("MainWindow", "Modify Ignition Points:"))
        self.label_17.setText(_translate("MainWindow", "Axis:"))
        self._ign_pt_axis_combo_box.setCurrentText(_translate("MainWindow", "Horizontal"))
        self._ign_pt_axis_combo_box.setItemText(0, _translate("MainWindow", "Horizontal"))
        self._ign_pt_axis_combo_box.setItemText(1, _translate("MainWindow", "Vertical"))
        self.label_11.setText(_translate("MainWindow", "Range:"))
        self.label_13.setText(_translate("MainWindow", "-"))
        self.label_14.setText(_translate("MainWindow", "Row/Column:"))
        self.label_16.setText(_translate("MainWindow", "Time Range:"))
        self.label_15.setText(_translate("MainWindow", "Ignition:"))
        self._ign_pt_add_rm_combo_box.setCurrentText(_translate("MainWindow", "Add"))
        self._ign_pt_add_rm_combo_box.setItemText(0, _translate("MainWindow", "Add"))
        self._ign_pt_add_rm_combo_box.setItemText(1, _translate("MainWindow", "Remove"))
        self.modify_ign_pts_button.setText(_translate("MainWindow", "Modify"))
        self._tab_widget.setTabText(self._tab_widget.indexOf(self.ignition_point_legend_tab), _translate("MainWindow", "Ignition Points"))
        self._sim_title_label.setText(_translate("MainWindow", "Simulation Title:"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_export.setTitle(_translate("MainWindow", "Export"))
        self.menu_settings.setTitle(_translate("MainWindow", "Settings"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.menu_simulation.setTitle(_translate("MainWindow", "Simulation"))
        self.menu_import.setTitle(_translate("MainWindow", "Import"))
        self.action_create_environment.setText(_translate("MainWindow", "Create Environment"))
        self.action_create_environment.setToolTip(_translate("MainWindow", "Import a GeoTIFF file"))
        self.action_import_environment.setText(_translate("MainWindow", "Environment"))
        self.action_import_environment.setToolTip(_translate("MainWindow", "Import an FDS file"))
        self.action_export_simulation.setText(_translate("MainWindow", "Simulation"))
        self.action_export_summary_file.setText(_translate("MainWindow", "Summary File"))
        self.action_export_environment.setText(_translate("MainWindow", "Environment"))
        self.action_export_environment.setToolTip(_translate("MainWindow", "Export the currently loaded FDS file with modifications"))
        self.action_import_simulation.setText(_translate("MainWindow", "Simulation"))
        self.action_import_summary_file.setText(_translate("MainWindow", "Summary File"))
        self.action_select_output_files.setText(_translate("MainWindow", "Select Output Files"))
        self.action_select_output_files.setToolTip(_translate("MainWindow", "Select the types of output files you would like"))
        self.action_run_sim.setText(_translate("MainWindow", "Run"))
        self.action_run_sim.setToolTip(_translate("MainWindow", "Run the currently loaded FDS file"))
        self.action_view_sim.setText(_translate("MainWindow", "View"))
        self.action_view_sim.setToolTip(_translate("MainWindow", "View the results of a simulation in Smokeview"))
        self.action_user_settings.setText(_translate("MainWindow", "User Settings"))
        self.action_user_settings.setToolTip(_translate("MainWindow", "View and modify user settings"))
        self.action_about.setText(_translate("MainWindow", "About"))
        self.action_about.setToolTip(_translate("MainWindow", "Information about this program"))
        self.action_import_fuel_map.setText(_translate("MainWindow", "Fuel Map"))
        self.action_import_fuel_map.setToolTip(_translate("MainWindow", "Import an Ascii grid Fuel Map"))
        self.action_import_dem.setText(_translate("MainWindow", "Digital Elevation Model"))
        self.action_import_dem.setToolTip(_translate("MainWindow", "Import an Ascii grid Digital Elevation Model"))
        self.action_export_fuel_map.setText(_translate("MainWindow", "Fuel Map"))
        self.action_export_fuel_map.setToolTip(_translate("MainWindow", "Export the currently loaded Fuel Map"))
        self.action_export_dem.setText(_translate("MainWindow", "Digital Elevation Model"))
        self.action_export_dem.setToolTip(_translate("MainWindow", "Export the currently loaded Digital Elevation Model"))
        self.action_ascii_to_fds.setText(_translate("MainWindow", "Ascii to FDS"))

